version: '3'

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    volumes:
      - ./data:/data
    environment:
      ZINCSEARCH_DATA_DIR: "/data"
      ZINC_FIRST_ADMIN_USER: "admin"
      ZINC_FIRST_ADMIN_PASSWORD: "admin"
    ports:
      - "4080:4080"
    container_name: zincsearch

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - zincsearch
    environment:
      ZINCSEARCH_API_URL: "http://zincsearch"
      ZINCSEARCH_API_PORT: 4080
      ZINCSEARCH_API_AUTHORIZATION: "Basic YWRtaW46YWRtaW4="

  frontend:
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
